config/routes.rb
Rails.application.routes.draw do
 


  resources :genres do
    resources :books
    end
    
root "genres#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :genre
  end
  

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :books, :dependent => :destroy
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  # GET /genres/1/books
  def index
    # For URL like /genres/1/books
    # Get the genre with id=1
    @genre = Genre.find(params[:genre_id])
    # Access all books for that genre
    @books = @genre.books
  end
  
  # GET /genres/1/books/2
  def show
    @genre = Genre.find(params[:genre_id])
    # For URL like /genres/1/books/2
    # Find an book in genres 1 that has id=2
    @book = @genre.books.find(params[:id])
      
  end

  
  
  # GET /genres/1/books/new
  def new
  @genre = Genre.find(params[:genre_id])
  # Associate an book object with genre 1
  @book = @genre.books.build
  end
  
  # POST /genres/1/books
  #def create
 # @genre = Genre.find(params[:genre_id])
  # For URL like /genres/1/books
  # Populate an book associate with genre 1 with form data
  # genre will be associated with the book
  # @book = @genre.books.build(params.require(:book).permit!)
  #@book = @genre.books.build(params.require(:book).permit(:details))
 # if @book.save
  # Save the book successfully
 # redirect_to genre_book_url(@genre, @book)
  #else
  #render :action => "new"
 # end
 # end

 def create
  @genre = Genre.find(params[:genre_id])
  # Build a new book associated with the genre
  @book = @genre.books.build(params.require(:book).permit!)
  
  if @book.save
    # Save the book successfully and redirect
    redirect_to genre_book_path(@genre, @book), notice: 'Book was successfully created.'
  else
    # Render the new template with errors
    render :new
  end
end
  
  # GET /genres/1/books/2/edit
  def edit
  @genre = Genre.find(params[:genre_id])
  # For URL like /genres/1/books/2/edit
  # Get book id=2 for genre 1
  @book = @genre.books.find(params[:id])
  end
  
  # PUT /genres/1/books/2
  def update
    @genre = Genre.find(params[:genre_id])
    @book = Book.find(params[:id])
  
    if @book.update(params.require(:book).permit(:details))
      # Save the book successfully
      redirect_to genre_books_path(@genre)
    else
      render :action => "edit"
    end
  end
  
  # DELETE /genres/1/books/2
  def destroy
  @genre = Genre.find(params[:genre_id])
  @book = Book.find(params[:id])
  @book.destroy
  respond_to do |format|
  format.html { redirect_to genre_books_path(@genre) }
  format.xml { head :ok }
  end
  end
  
  end
  

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  # GET /genres or /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1 or /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres or /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1 or /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to genre_url(@genre), notice: "Genre was successfully updated." }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1 or /genres/1.json
  def destroy
    @genre.destroy!

    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genre_params
      params.require(:genre).permit(:name, :description, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Synopsis:</strong>
    <%= book.synopsis %>
  </p>


</div>

app/views/books/_form.html.erb
<%= form_for([@genre, @book]) do |f| %>
  <% if @book.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@book.errors.count, "error")%>
  prohibited this review from being saved:</h2>
  <ul>
  <% @book.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
  </ul>
  </div>
  <% end %>
  <div class="field">
  <p>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "custom-text-field" %>
  </div>

  <br />

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, class: "custom-text-field" %>
  </div>

  <br />

  <div class="field">
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis, class: "custom-text-field" %>
  </div>

  <br />
  <div class="actions">
    <%= f.submit "SAVE", class: "btn btn-outline-dark btn-sm" %>
  </div>
  </p>
  </div>
  
  <% end %>
  
  




  

app/views/books/edit.html.erb
<h1>EDIT BOOKGRFRFYERTY</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 centredisplay">   
    <br />
    <p class="headingtext">Edit book in the <%= @genre.name %> section</p>
    <br />
        <%= render "form", book: @book %>
        <p id="notice"><%= notice %></p>
         <%= link_to "Back to genres", genre_books_path %>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/books/index.html.erb
<h1>INDEX BOOK</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 centredisplay">   
    <br />
    <p class="headingtext">Books in the <%= @genre.name %> section</p>
    <br />
    <%= link_to 'ADD NEW BOOK TO GENRE', new_genre_book_path(@genre), class: 'btn btn-outline-success btn-sm' %>
    
    <%= link_to 'BACK TO FULL CATALOGUE', genres_path, class: 'btn btn-outline-dark btn-sm' %>
    <br />
    <br />
    
    <div id="books">
    <% @genre.books.each do |book| %>
        <hr />
     <%= render book %>
    <div class="buttons">
     <%= link_to 'EDIT BOOK', edit_genre_book_path(@genre, book), class: 'btn btn-outline-success btn-sm' %>
    <%= button_to "DELETE BOOK", genre_book_path(@genre, book), method: :delete, class: 'btn btn-outline-danger btn-sm'  %>
    </div>

     <hr />
    
     <% end %>
    </div>
      
      

    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>











<div>



</div>

app/views/books/new.html.erb
<h1>NEW BOOK</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 centredisplay">   
    <br />
    <p class="headingtext">Add a new book to the <%= @genre.name %> section</p>
    <br />
        <%= render "form", book: @book %>
        
         <%= link_to "BACK TO FULL CATALOGUE", genre_books_path, class: "btn btn-outline-dark btn-sm" %>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/books/show.html.erb
<h1>SHOW BOOKS</h1>
<div class="container-fluid">
  <div class="row">
    
    <div class="col-lg-3">
    </div>
    
    <div class="col-lg-6 centredisplay">   
      <br />
      <p class="headingtext">BOOK ADDED TO <%= @genre.name %> SECTION</p>
      <br />
      <%= link_to 'ADD NEW BOOK TO GENRE', new_genre_book_path(@genre), class: 'btn btn-outline-success btn-sm' %>
      <%= link_to 'BACK TO FULL CATALOGUE', genres_path, class: 'btn btn-outline-dark btn-sm' %>
      <br />
      <br />
      <div id="books">
        <% if @genre.books.any? %>
          <% @genre.books.each do |book| %>
            <hr />
            <%= render book %>
            
            <div class="buttons">
              <%= link_to 'EDIT BOOK', edit_genre_book_path(@genre, @book), class: 'btn btn-outline-success btn-sm' %>
              <%= button_to 'DELETE BOOK', genre_book_path(@genre, book), method: :delete, class: 'btn btn-outline-danger btn-sm' %>
            </div>
          <% end %>
        <% else %>
          <p class="noticeok">No books currently in this genre - add one below.</p>
        <% end %>
        <hr />
      </div>
    </div>
    
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |form| %>
  <% if genre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
        <% genre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "custom-text-field" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "custom-text-field" %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location, class: "custom-text-field" %>
  </div>
<br />
  <div>
    <%= form.submit "SAVE", class: "btn btn-outline-dark btn-sm" %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<div id="<%= dom_id genre %>">
  <p>
    <strong>Name:</strong>
    <%= genre.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= genre.description %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= genre.location %>
  </p>

</div>

app/views/genres/edit.html.erb
<h1>EDIT GENRE</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6"> 
      <br />  
      <p class="headingtext">EDIT GENRE</p>
      <div class="centredisplay">
        <%= render "form", genre: @genre %>
        <br />
        
        <%= link_to "BACK TO FULL CATALOGUE", genres_path, class: "btn btn-outline-dark btn-sm" %>
      </div>    
    <div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/genres/index.html.erb
<h1>INDEX GENRE</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 centredisplay">
      <br />
      <p class="headingtext"><%= image_tag 'book_categoriser.png'  %></p>
      <p class="headingtext">FULL CATALOGUE</p>
      <br /><br />
      <%= link_to "ADD NEW GENRE", new_genre_path, class: "btn btn-outline-success" %>
      <br /><br />
      <hr class="hr" />
      <div>
        <% @genres.each do |genre| %>
          <%= render genre %>
          <br />
          <div class="buttons">
          <%= link_to "SHOW GENRE", genre, class: "btn btn-outline-dark" %>
          
          <%= link_to 'EDIT GENRE', edit_genre_path(genre), class: "btn btn-outline-success" %> 
          <%= button_to "DELETE GENRE", genre, method: :delete, class: "btn btn-outline-danger" %>
          </div>
          <br />
          <hr class="hr" />
           <% end %>
      </div>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/genres/new.html.erb
<h1>NEW GENRE</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 centredisplay">   
    <p class="headingtext">ADD NEW GENRE</p>
        <%= render "form", genre: @genre %>
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/genres/show.html.erb
<h1>SHOW GENRE</h1>
123
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6 centredisplay">   
    <!-- Display the books of a genre -->
<br />
    <p class="headingtext"><%= @genre.name %></p>
    <%= link_to 'ADD NEW BOOK TO GENRE', new_genre_book_path(@genre), class: 'btn btn-outline-success btn-sm' %>
    <%= link_to 'BACK TO FULL CATALOGUE', genres_path, class: 'btn btn-outline-dark btn-sm' %> 
    <br />    

<br />
<p><strong>Books in <%= @genre.name %></strong></p>





<div id="books centredisplay">
  <% if @genre.books.any? %>
    <% @genre.books.each do |book| %>
      <div class="book">
      <hr />  
      <%= render book%>
        
        <%= button_to "DELETE THIS BOOK", genre_book_path(@genre, book), method: :delete, class: 'btn btn-outline-danger btn-sm'  %>
        <hr />      
        </div>
    <% end %>
  <% else %>
    <p class="noticeok">No books currently in this genre - add one below.</p>
  <% end %>

</div>
<br />

    
    </div>
    <div class="col-lg-3">
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg ml-auto border-bottom border-body">
  <div class="container-fluid">
    <%= link_to image_tag('logo.png'), genres_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          
          <%= link_to 'FULL CATALOGUE', genres_path, class: 'btn btn-outline-dark btn-lg' %>
        </li>
        
        </li>
        
        
      </ul>
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCategoriser</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href='https://fonts.googleapis.com/css2?family=Rosario:ital,wght@0,300..700;1,300..700&display=swap' rel='stylesheet' type='text/css'>
  </head>

  <body>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2">
    </div>  
    <div class="col-lg-8">
    <%= render 'layouts/navbar'%>
    <%= yield %>
    </div>
    <div class="col-lg-2">
    </div>
  </div>
</div>
</body>
</html>